# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work +define+COCOTB_SIM -sv -timescale 1ns/1ps -mfcu +acc  F:/ic_design/repos/python_environment/FiFO_cocotb/fifo.v
vsim  -onfinish exit -pli F:/Python/Lib/site-packages/cocotb/libs/cocotbvpi_modelsim.dll   sim_build/work.fifo
onbreak resume
run -all
quit
